FROM node:16-alpine as builder

WORKDIR /app

# install node modules
COPY package.json .
COPY yarn.lock .
RUN yarn --frozen-lockfile

# build bundle
COPY . .
RUN yarn build

# nginx
FROM nginx:1.21.0-alpine as production
ENV NODE_ENV production

# nginx config
RUN rm -rf /etc/nginx/conf.d
COPY conf /etc/nginx

# static build
# added /api at the end to serve from subfolder
COPY --from=builder /app/build /usr/share/nginx/html/api 

# default port exposure
EXPOSE 5000


CMD ["nginx", "-g", "daemon off;"]
